[formatter.nixfmt]
command = "nixfmt"
excludes = []
includes = ["*.nix"]
options = []

[global]
excludes = [
    "*.lock",
    "*.patch",
    "package-lock.json",
    "go.mod",
    "go.sum",
    ".gitignore",
    ".gitmodules",
    ".hgignore",
    ".svnignore",
]
on-unmatched = "warn"
